title: Bryan Chavez
description: I am passionate about turning data into actionable insights and building scalable AI solutions. Eager to apply both softwareengineering fundamentals and advanced AI techniques to drive innovation.
show_downloads: False
theme: jekyll-theme-slate
