title: Bryan Chavez
description: I am passionate about turning data into actionable insights and building scalable AI solutions.
show_downloads: False
theme: jekyll-theme-slate
github:
  is_project_page: false
linkedin_username: bryan-chavez-4900462b4
